### ISSUE TITLE
From GeoSMART JupyterBook @wsauthoff

### ISSUE THREAD

**Issue by wsauthoff** [geo-smart/deepicedrainpipe#21]

**Comment by wsauthoff** [comment]
Open issue accidentally. Reopened in attempt to see if I could delete issue entirely. Permissions on geo-smart org don't seem to allow issue deletion.

**Comment by weiji14** [comment]
I don't think there's actually a way to delete issues on GitHub, only lock conversations.

**Comment by wsauthoff** [comment]
It seems like it is possible from reading this GitHub doc: https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue
